import { useMemo, useState } from 'react'
import { motion } from 'framer-motion'
import { Clock, Gauge, MapPin, Route as RouteIcon, Timer } from 'lucide-react'
import { cn } from '@/lib/cn'
import { formatStation } from '@/lib/formatters'
import { fadeUp } from '@/lib/motion'
import type { ApiPatrolRoute } from '@/types/api'
import { StationRouteSelector } from './StationRouteSelector'
import { RouteMapPanel } from './RouteMapPanel'
import { RouteStopList } from './RouteStopList'

interface RoutePlannerPanelProps {
  routes: ApiPatrolRoute[]
  routingModeFallback?: string | null
}

function num(r: ApiPatrolRoute, ...keys: string[]): number | null {
  for (const k of keys) {
    const v = r[k]
    if (typeof v === 'number' && Number.isFinite(v)) return v
  }
  return null
}

export function RoutePlannerPanel({ routes, routingModeFallback }: RoutePlannerPanelProps) {
  const options = useMemo(
    () =>
      routes.map((r) => ({
        station: String(r.assigned_station ?? r.route_id ?? '—'),
        routeId: String(r.route_id ?? ''),
        stops: r.stops?.length ?? r.stop_count ?? 0,
      })),
    [routes],
  )

  const [station, setStation] = useState(options[0]?.station ?? '')

  const route = useMemo(
    () => routes.find((r) => String(r.assigned_station ?? r.route_id) === station) ?? routes[0] ?? null,
    [routes, station],
  )

  if (routes.length === 0) {
    return (
      <div className="rounded-2xl border border-dashed border-btp-cyan/20 bg-civic-navy/40 p-10 text-center">
        <RouteIcon className="mx-auto mb-3 h-8 w-8 text-btp-cyan/50" />
        <p className="text-sm font-semibold text-civic-white">No patrol routes available</p>
        <p className="mt-1 text-xs text-civic-ivory/55">
          Routes are generated by the M10 optimizer after the 4 AM agent run.
        </p>
      </div>
    )
  }

  const distance = route ? num(route, 'total_distance_km', 'estimated_route_km') : null
  const duration = route ? num(route, 'estimated_duration_min', 'estimated_total_minutes') : null
  const officerHours = route ? num(route, 'officer_hours') : null
  const routingMode = String(route?.routing_mode ?? routingModeFallback ?? '—')
  const stopCount = route?.stops?.length ?? route?.stop_count ?? 0

  const summary: Array<{ icon: typeof Clock; label: string; value: string }> = [
    { icon: RouteIcon, label: 'Route ID', value: String(route?.route_id ?? '—') },
    { icon: Gauge, label: 'Routing', value: routingMode },
    { icon: MapPin, label: 'Stops', value: String(stopCount) },
    { icon: Timer, label: 'Distance', value: distance != null ? `${distance.toFixed(1)} km` : '—' },
    { icon: Clock, label: 'Duration', value: duration != null ? `${Math.round(duration)} min` : '—' },
    { icon: Clock, label: 'Officer-hrs', value: officerHours != null ? officerHours.toFixed(2) : '—' },
  ]

  return (
    <div className="space-y-4">
      <div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between">
        <div className="w-full lg:max-w-xs">
          <StationRouteSelector options={options} value={station} onChange={setStation} />
        </div>
        <p className="text-sm font-semibold text-civic-white">
          {formatStation(String(route?.assigned_station ?? '—'))}
          <span className="ml-2 text-xs font-normal text-civic-ivory/50">station patrol route</span>
        </p>
      </div>

      <motion.div
        variants={fadeUp}
        initial="hidden"
        animate="visible"
        className="grid grid-cols-2 gap-2.5 sm:grid-cols-3 lg:grid-cols-6"
      >
        {summary.map((s) => {
          const Icon = s.icon
          return (
            <div key={s.label} className="rounded-xl border border-btp-cyan/12 bg-civic-navy/55 px-3 py-2.5 backdrop-blur-xl">
              <p className="flex items-center gap-1 text-[9px] font-bold uppercase tracking-wide text-civic-ivory/45">
                <Icon className="h-3 w-3 text-status-route" />
                {s.label}
              </p>
              <p className="mt-1 truncate text-sm font-bold capitalize text-civic-white">{s.value}</p>
            </div>
          )
        })}
      </motion.div>

      <div className="grid gap-4 lg:grid-cols-3">
        <RouteMapPanel
          route={route}
          className={cn('h-[320px] sm:h-[400px] lg:col-span-2 lg:h-[clamp(360px,50vh,540px)]')}
        />
        <div className="lg:h-[clamp(360px,50vh,540px)] lg:overflow-y-auto lg:pr-1 scrollbar-thin">
          <RouteStopList stops={route?.stops ?? []} />
        </div>
      </div>
    </div>
  )
}
